
class Common:
    def __init__(self):
        super().__init__()
        self.gestdirDes = 'C:\\Users\\ngome\\Downloads\\' # directorio de descarga
        self.gestExpOKXPath = '//*[@id="downloadFileModal"]/div/div[1]/span' # EXPORTACIÓN EXITOSA
        self.gestDesXPath = '/html/body/div[7]/div/form/div/div/a' # DESCARGAR

        self.gestExpID = 'excelExport'
        self.gestDesPlaID = 'excelDownload'
        self.gestCarPlaID = 'excelUpload'
        self.gestVolverID = 'back'
        self.gestVolverListID = 'backToList'
        self.gestHacDevID = 'returnPurchaseOrder'
        self.gestAvSeaID = 'advancedSearch'
        self.gestDesID = 'downloadLink'
        self.gestMensajeID = 'modalMessage'
        self.gestPrecioID = 'price'
        self.gestGBID = 'saveDraft'
        self.gestAlCanID = 'amount'
        self.gestConfirmarID = 'sendDelivery'
        self.gestRechazarID = 'rejectDelivery'
        self.gestReferencia1TXT = 'Referencia*'
        self.gestReferencia2TXT = 'Referencia'
        self.gestReferencia3TXT = 'Ref.'
        self.gestHacDevTXT = 'Hacer devolución'
        self.gestExpTXT = 'Exportar'
        self.gestExp2TXT = 'EXPORTAR'
        self.gestDesTXT = 'DESCARGAR'
        self.gestExpOKTXT = 'EXPORTACIÓN EXITOSA'
        self.gestVolverTXT = 'Volver'
        self.gestAvSeaTXT = 'Búsqueda avanzada'
        self.gestAvSea2TXT = 'BÚSQUEDA AVANZADA'
        self.gestMMCoTXT = 'Mostrar más columnas'
        self.gestBusTXT = 'Buscar:'
        self.gestBus2TXT = 'Buscar'
        self.gestFilTXT = 'Filtros:'
        self.gestKOTXT = 'Cancelar'
        self.gestAOKTXT = 'Aceptar'
        self.gestGOKTXT = 'Guardar'
        self.gestGBTXT = 'Guardar borrador'
        self.gestConfirmarTXT = 'Confirmar'
        self.gestRechazarTXT = 'Rechazar'
        self.gestGKOTXT = 'No guardar'
        self.gestVSGTXT = 'Volver sin guardar'
        self.gestGVTXT = 'Guardar y volver'
        self.gestMOKTXT = 'Modificar'
        self.gestDOKTXT = 'Eliminar'
        self.gestCOKTXT=  'Cerrar'
        self.gestNomTXT = 'Nombre'
        self.gestNom2TXT = 'Nombre*'
        self.gestCanTXT = 'Cantidad'
        self.gestCan2TXT = 'Cantidad:'
        self.gestUniTXT = 'Unidad'
        self.gestUni2TXT = 'Unidades'
        self.gestUni3TXT = 'Unidad:'
        self.gestStaTXT = 'Estado'
        self.gestAccTXT = 'Acciones'
        self.gestAñadirTXT = 'Añadir'
        self.gestProdTXT = 'PRODUCTOS'
        self.gestProd2TXT = 'Productos'
        self.gestAllTXT = 'Todas'
        self.gestFecTXT = 'Fecha'
        self.gestFec2TXT = 'Fecha:'
        self.gestDesPlaTXT = 'Descargar plantilla'
        self.gestCarPlaTXT = 'Cargar plantilla'
        self.gestFecCreTXT = 'Fecha de creación'
        self.gestFecComTXT = 'Fecha de compra'
        self.gestPrecioTXT = 'Precio'
        self.gestPrecioUnitTXT = 'Precio unitario (€):'
        self.gestPrecioUnit2TXT = 'Precio unitario (€)'
        self.gestDescuentoTXT = 'Descuento'
        self.gestDescripTXT = 'Descripción'
        self.gestCantidad0TXT = '0'
        self.gestCantidad1TXT = '1'
        self.gestCantidad2TXT = '2'
        self.gestSubtotalTXT ='Subtotal:'
        self.gestSubtotal2TXT = 'Subtotal'
        self.gestSubtotal3TXT = '€'
        self.gestProvTXT = 'Proveedor'
        self.gestProv2TXT = 'Proveedor*'
        self.gestProv3TXT = 'Proveedores'
        self.gestImporteTXT = 'Importe'
        self.gestImporteDTXT = 'Importe desc.'
        self.gestTotal1TXT = 'Total'
        self.gestTotal2TXT = 'Total:'
        self.gestTotalITXT = 'Total + IVA:'
        self.gestTotalI2TXT = 'Total + IVA'
        self.gestUbic1TXT = 'Ubicación'
        self.gestUbic2TXT = 'Ubicaciones'
        self.gestNotasTXT = 'Notas'
        self.gestAlmacenTXT = 'Almacén'
        self.gestAlPed1TXT = 'Pedidos'
        self.gestAlPed2TXT = 'Pedido'
        self.gestAlIVATXT = 'IVA'


        self.gestFIInput = '01/01/2024' # Fecha inicio
        self.gestFFInput = '01/01/2025'  # Fecha fin





