class GestionVentas:
    def __init__(self):
        super().__init__()
        # Primeras comprobaciones: URL cargada, primer texto, título de la página
        self.url = 'https://tamus.hi-iberia.es/sales/tickethistory'
        self.titPagGestVenXPath = '/html/body/div[2]/div[2]/div[1]/div[1]/div'
        self.titPagGestVenTXT = 'HISTORIAL DE TICKETS'
        self.nomPagGestVen = 'Gestión de Ventas - Historial de tickets'

        # Página principal
        self.gestVenResXPath = '//*[@id="restaurant_list"]/div[9]'
        self.gestVenResTXT = 'LTL Fleming'
        self.gestVenTBuXPath = '//*[@id="tickethistory-action"]/div[1]/span'
        self.gestVenTBuTXT = 'Buscar:'
        self.gestVenFec1XPath = '//*[@id="tickethistory-action"]/div[1]/div[2]/div/span[1]'
        self.gestVenFec1TXT = 'Fecha:'
        self.gestVenFec2XPath = '//*[@id="tickethistory-action"]/div[1]/div[2]/div/span[2]'
        self.gestVenFec2TXT = '11/09/2024 - 11/10/2024'
        self.gestVenBusXPath = '//*[@id="tickethistory-action"]/div[1]/div[1]/input'
        self.gestVenBusFac = 'A'
        self.gestVenMosXPath = '//*[@id="tickethistory-action"]/div[2]'
        self.gestVenMosTXT = 'Mostrando del0al0de0tickets'

        # Menú lateral
        self.latPagGestVHTXPath = '//*[@id="lateralmenu"]/ul/li[1]'
        self.latPagGestVHTTXT = 'Historial de tickets'
        self.latPagGestTPVXPath = '//*[@id="lateralmenu"]/ul/li[2]'
        self.latPagGestTPVTXT = 'Facturas de TPV'
        self.latPagGestVHCXPath = '//*[@id="lateralmenu"]/ul/li[3]'
        self.latPagGestVHCTXT = 'Historial de cierres'
        self.latPagGestVMCXPath = '//*[@id="lateralmenu"]/ul/li[4]'
        self.latPagGestVMCTXT = 'Movimientos de caja'
        self.latPagGestVLMXPath = '//*[@id="lateralmenu"]/ul/li[5]'
        self.latPagGestVLMTXT = 'Líneas modificadas'
        self.latPagGestVPIXPath = '//*[@id="lateralmenu"]/ul/li[6]'
        self.latPagGestVPITXT = 'Proformas impresas'
        self.latPagGestVPAXPath = '//*[@id="lateralmenu"]/ul/li[7]'
        self.latPagGestVPATXT = 'Promociones aplicadas'
        self.latPagGestVIAXPath = '//*[@id="lateralmenu"]/ul/li[8]'
        self.latPagGestVIATXT = 'Invitaciones aplicadas'
        self.latPagGestVCoXPath = '//*[@id="lateralmenu"]/ul/li[9]'
        self.latPagGestVCoTXT = 'Comandas'
        self.latPagGestVPrXPath = '//*[@id="lateralmenu"]/ul/li[10]'
        self.latPagGestVPrTXT = 'Propinas'
        self.latPagGestVInXPath = '//*[@id="lateralmenu"]/ul/li[11]'
        self.latPagGestVInTXT = 'Informes'
        self.latPagGestVIPXPath = '//*[@id="lateralmenu"]/ul/li[12]'
        self.latPagGestVIPTXT = 'Informes personalizados'
        self.latPagGestVVOnXPath = '//*[@id="lateralmenu"]/ul/li[13]'
        self.latPagGestVVOnTXT = 'Visualización online'

        # Posiciones de columnas
        self.gestVenCol01XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[1]'
        self.gestVenCol02XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[2]'
        self.gestVenCol03XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[3]'
        self.gestVenCol04XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[4]'
        self.gestVenCol05XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[5]'
        self.gestVenCol06XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[6]'
        self.gestVenCol07XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[7]'
        self.gestVenCol08XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[8]'
        self.gestVenCol09XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[9]'
        self.gestVenCol10XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[10]'
        self.gestVenCol11XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[11]'
        self.gestVenCol12XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[12]'
        self.gestVenCol13XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[13]'
        self.gestVenCol14XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[14]'
        self.gestVenCol15XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[15]'
        self.gestVenCol16XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[16]'
        self.gestVenCol17XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[17]'
        self.gestVenCol18XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[18]'
        self.gestVenCol19XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[19]'
        self.gestVenCol20XPath = '//*[@id="tickethistory-table"]/table/thead/tr[1]/th[20]'

        # Columnas
        self.gestVenColFacTXT = '#Factura'
        self.gestVenColFFaTXT = 'Fecha facturación'
        self.gestVenColImpTXT = 'Importe'
        self.gestVenColCieTXT = '#Cierre'
        self.gestVenColMesTXT = 'Mesa'
        self.gestVenColAccTXT = 'Acciones'

        # Más columnas
        self.gestVenColFApTXT = 'Fecha apertura'
        self.gestVenColBasTXT = 'Base'
        self.gestVenColIvaTXT = 'IVA'
        self.gestVenColFpaTXT = 'FPago'
        self.gestVenColCajTXT = 'Caja'
        self.gestVenColComTXT = 'Comensales'
        self.gestVenColEdMTXT = 'Edad Media'
        self.gestVenColTMeTXT = 'Tipo de Mesa'
        self.gestVenColHabTXT = '#Habit.'
        self.gestVenColADoTXT = 'A domicilio'

        # Menú: más columnas
        self.gestVenMCoXPath = '//*[@id="tickethistory-table"]/div[2]/label/div/span'  # Mostrar mas columnas
        self.gestVenMCoTXT = 'Mostrar más columnas'
        self.gestVenMCoNReXPath = '//*[@id="columnsModal"]/div/form/div[1]/div[1]/div[1]/label/div'
        self.gestVenMCoNReTXT = 'Número de recibo'
        self.gestVenMCoFApXPath = '//*[@id="columnsModal"]/div/form/div[1]/div[2]/div[1]/label/div'
        self.gestVenMCoFApTXT = 'Fecha apertura'
        self.gestVenMCoImpXPath = '//*[@id="columnsModal"]/div/form/div[1]/div[3]/div[1]/label/div'
        self.gestVenMCoImpTXT = 'Importe'
        self.gestVenMCoCieXPath = '//*[@id="columnsModal"]/div/form/div[1]/div[4]/div[1]/label/div'
        self.gestVenMCoCieTXT = '#Cierre'
        self.gestVenMCoEmpXPath = '//*[@id="columnsModal"]/div/form/div[1]/div[5]/div[1]/label/div'
        self.gestVenMCoEmpTXT = 'Empleado'
        self.gestVenMCoCajXPath = '//*[@id="columnsModal"]/div/form/div[1]/div[6]/div[1]/label/div'
        self.gestVenMCoCajTXT = 'Caja'
        self.gestVenMCoAdoXPath = '//*[@id="columnsModal"]/div/form/div[1]/div[7]/div[1]/label/div'
        self.gestVenMCoAdoTXT = 'A domicilio'
        self.gestVenMCoNHaXPath = '//*[@id="columnsModal"]/div/form/div[1]/div[1]/div[2]/label/div'
        self.gestVenMCoNHaTXT = 'Nº Habitación'
        self.gestVenMCoFFaXPath = '//*[@id="columnsModal"]/div/form/div[1]/div[2]/div[2]/label/div'
        self.gestVenMCoFFaTXT = 'Fecha facturación'
        self.gestVenMCoIvaXPath = '//*[@id="columnsModal"]/div/form/div[1]/div[3]/div[2]/label/div'
        self.gestVenMCoIvaTXT = 'IVA'
        self.gestVenMCoFpaXPath = '//*[@id="columnsModal"]/div/form/div[1]/div[4]/div[2]/label/div'
        self.gestVenMCoFpaTXT = 'Forma de pago'
        self.gestVenMCoMesXPath = '//*[@id="columnsModal"]/div/form/div[1]/div[5]/div[2]/label/div'
        self.gestVenMCoMesTXT = 'Mesa'
        self.gestVenMCoComXPath = '//*[@id="columnsModal"]/div/form/div[1]/div[6]/div[2]/label/div'
        self.gestVenMCoComTXT = 'Comensales'
        self.gestVenMCoEMeXPath = '//*[@id="columnsModal"]/div/form/div[1]/div[7]/div[2]/label/div'
        self.gestVenMCoEMeTXT = 'Edad Media'
        self.gestVenMMCConXPath = '//*[@id="tickethistory-table"]/div[2]/i'  # configuración Mostrar más columnas
        self.gestVenMMCNomXPath = ''
        self.gestVenMMCGuaXPath = '//*[@id="columnsModal"]/div/form/div[3]/button[2]'  # Guardar cambios en Mas columnas
        self.gestVenMMCCanXPath = '//*[@id="columnsModal"]/div/form/div[3]/button[1]'  # Cancelar cambios en Mas columnas

        # visual online
        self.gestVenVOTitTXT = 'VISUALIZACIÓN ONLINE'
        self.gestVenVOLDiXPath = '//*[@id="online-space"]/h2'
        self.gestVenVOLDiTXT = 'LOCALES DISPONIBLES'
        self.gestVenVOResXPath ='//*[@id="restaurant-list"]/div/div[2]/div[1]'  # restaurante
        self.gestVenVOResTXT = 'LTL FLEMING'
        self.gestVenVOFecXPath = '//*[@id="restaurant-list"]/div/div[2]/div[2]'
        self.gestVenVOFecTXT ='29/07/2024 - 09:09'
        self.gestVenVOStaXPath = '//*[@id="restaurant-list"]/div/div[2]/div[3]/span'
        self.gestVenVOStaTXT = 'CERRADO - 00:01'
        self.gestVenVOTotXPath = '//*[@id="restaurant-list"]/div/div[2]/div[4]/span[1]'
        self.gestVenVOTotTXT = 'Total:'
        # Visual Online -->  VO
        self.gestVenVOImpXPath = '//*[@id="restaurant-list"]/div/div[2]/div[4]/span[2]'
        self.gestVenVOImpTXT = '2249.15€'
        self.gestVenVOPteXPath = '//*[@id="restaurant-list"]/div/div[2]/div[5]/span[1]'
        self.gestVenVOPteTXT = 'Pendiente en mesa:'
        self.gestVenVOIPteXPath = '//*[@id="restaurant-list"]/div/div[2]/div[5]/span[2]'
        self.gestVenVOIPteTXT = '0.00€'
        self.gestVenVOInfXPath = '//*[@id="restaurant-list"]/div/div[2]/div[6]'
        self.gestVenVOInfTXT = 'Visualizar informe X'
        self.gestVenVOProXPath = '//*[@id="restaurant-list"]/div/div[2]/div[7]'
        self.gestVenVOProTXT = 'Visualizar productos'

        # Visual Online Informe --> VOI
        self.gestVenVOITitXPath = '//*[@id="xModal"]/div/div[1]/span'
        self.gestVenVOIPagXPath = '//*[@id="xModal"]/div/form/div[1]/div[1]/div[1]/table/thead/tr/th[1]'
        self.gestVenVOIPagTXT = 'Pagos'
        self.gestVenVOITotXPath = '//*[@id="xModal"]/div/form/div[1]/div[1]/div[1]/table/thead/tr/th[2]'
        self.gestVenVOITotTXT = 'Total'
        self.gestVenVOIUbeXPath = '//*[@id="payments"]/tr[1]/td[1]'
        self.gestVenVOIUbeTXT = 'Uber'
        self.gestVenVOIUbTXPath = '//*[@id="payments"]/tr[1]/td[2]'
        self.gestVenVOIUbTTXT = '212,40'
        self.gestVenVOIGloXPath = '//*[@id="payments"]/tr[2]/td[1]'
        self.gestVenVOIGloTXT = 'Glovo'
        self.gestVenVOIGlTXPath = '//*[@id="payments"]/tr[2]/td[2]'
        self.gestVenVOIGlTTXT = '189,70'
        self.gestVenVOIVisXPath = '//*[@id="payments"]/tr[3]/td[1]'
        self.gestVenVOIVisTXT = 'VISA'
        self.gestVenVOIViTXPath = '//*[@id="payments"]/tr[3]/td[2]'
        self.gestVenVOIViTTXT = '1358,07'
        self.gestVenVOIJusXPath = '//*[@id="payments"]/tr[4]/td[1]'
        self.gestVenVOIJusTXT = 'Just Eat'
        self.gestVenVOIJuTXPath = '//*[@id="payments"]/tr[4]/td[2]'
        self.gestVenVOIJuTTXT = '37,10'
        self.gestVenVOICasXPath = '//*[@id="payments"]/tr[5]/td[1]'
        self.gestVenVOICasTXT = 'cash'
        self.gestVenVOICaTXPath = '//*[@id="payments"]/tr[5]/td[2]'
        self.gestVenVOICaTTXT = '451,88'
        self.gestVenVOIImpXPath = '//*[@id="xModal"]/div/form/div[1]/div[1]/div[2]/table/thead/tr/th[1]'
        self.gestVenVOIImpTXT = 'Impuestos'
        self.gestVenVOITo2XPath = '//*[@id="xModal"]/div/form/div[1]/div[1]/div[2]/table/thead/tr/th[2]'
        self.gestVenVOITo2TXT = 'Total'
        self.gestVenVOIIvaXPath = '//*[@id="taxes"]/tr/td[1]'
        self.gestVenVOIIvaTXT = 'IVA 10%'
        self.gestVenVOIIvTXPath = '//*[@id="taxes"]/tr/td[2]'
        self.gestVenVOIIvTTXT = '204,47'
        self.gestVenVOIFHCXPath = '//*[@id="xModal"]/div/form/div[1]/div[2]/div[1]/div[2]/span[1]'
        self.gestVenVOIFHCTXT = 'Fecha y hora de cierre'
        self.gestVenVOIFHCDXPath = '//*[@id="closeDate"]'
        self.gestVenVOIFHCDTXT = '29/07/2024 - 00:01'
        self.gestVenVOIFHSXPath = '//*[@id="xModal"]/div/form/div[1]/div[2]/div[1]/div[3]/span[1]'
        self.gestVenVOIFHSTXT = 'Fecha y hora de sincronización'
        self.gestVenVOIFHSDXPath = '//*[@id="syncDate"]'
        self.gestVenVOIFHSDTXT = '29/07/2024 - 09:09'
        self.gestVenVOIVenXPath = '//*[@id="xModal"]/div/form/div[1]/div[2]/div[2]/div[1]/span[1]'
        self.gestVenVOIVenTXT = 'Ventas'
        self.gestVenVOIVeDXPath = '//*[@id="sales"]'
        self.gestVenVOIVeDTXT = '66'
        self.gestVenVOIComXPath = '//*[@id="xModal"]/div/form/div[1]/div[2]/div[2]/div[2]/span[1]'
        self.gestVenVOIComTXT = 'Comensales'
        self.gestVenVOICoDXPath = '//*[@id="customers"]'
        self.gestVenVOICoDTXT = '135'
        self.gestVenVOISubXPath = '//*[@id="xModal"]/div/form/div[1]/div[2]/div[2]/div[3]/span[1]'
        self.gestVenVOISubTXT = 'Subtotal'
        self.gestVenVOISuDXPath = '//*[@id="subTotal"]'
        self.gestVenVOISuDTXT = '2044.68€'
        self.gestVenVOIImp2XPath = '//*[@id="xModal"]/div/form/div[1]/div[2]/div[2]/div[4]/span[1]'
        self.gestVenVOIImp2TXT = 'Impuestos'
        self.gestVenVOIImp2DXPath = '//*[@id="taxTotal"]'
        self.gestVenVOIImp2DTXT = '204.47€'
        self.gestVenVOITot3XPath = '//*[@id="xModal"]/div/form/div[1]/div[2]/div[2]/div[5]/span[1]'
        self.gestVenVOITot3TXT = 'TOTAL'
        self.gestVenVOITot3DXPath = '//*[@id="salesTotal"]'
        self.gestVenVOITot3DTXT = '2249.15€'
        self.gestVenVOIPteMXPath = '//*[@id="xModal"]/div/form/div[1]/div[2]/div[3]/div[1]/span[1]'
        self.gestVenVOIPteMTXT = 'Pendiente en mesa'
        self.gestVenVOIPteMDXPath = '//*[@id="pending"]'
        self.gestVenVOIPteMDTXT = '0.00€'
        self.gestVenVOITPtMXPath = '//*[@id="xModal"]/div/form/div[1]/div[2]/div[3]/div[2]/span[1]'
        self.gestVenVOITPtMTXT = 'TOTAL + Pendiente en mesa'
        self.gestVenVOITPtMDXPath = '//*[@id="pendingTotal"]'
        self.gestVenVOITPtMDTXT = '2249.15€'
        self.gestVenVOIPrAXPath = '//*[@id="xModal"]/div/form/div[1]/div[2]/div[4]/div[1]/span[1]'
        self.gestVenVOIPrATXT = 'Productos anulados'
        self.gestVenVOIPrADXPath = '//*[@id="cancelled"]'
        self.gestVenVOIPrADTXT = '5'
        self.gestVenVOILP0XPath = '//*[@id="xModal"]/div/form/div[1]/div[2]/div[4]/div[2]/span[1]'
        self.gestVenVOILP0TXT = 'Líneas puestas a 0'
        self.gestVenVOILP0DXPath = '//*[@id="lines_to_zero"]'
        self.gestVenVOILP0DTXT ='0'
        self.gestVenVOIPP0XPath = '//*[@id="xModal"]/div/form/div[1]/div[2]/div[4]/div[3]/span[1]'
        self.gestVenVOIPP0TXT = 'Productos puestos a 0'
        self.gestVenVOIPP0DXPath = '//*[@id="products_to_zero"]'
        self.gestVenVOIPP0DTXT = '0'
        self.gestVenVOIOcuXPath = '//*[@id="xModal"]/div/form/div[1]/div[2]/div[5]/div[1]/span[1]'
        self.gestVenVOIOcuTXT = 'Ocupación'
        self.gestVenVOIOcuDXPath = '//*[@id="occupation"]'
        self.gestVenVOIOcuDTXT = '0%'
        self.gestVenVOICoLXPath = '//*[@id="xModal"]/div/form/div[1]/div[2]/div[5]/div[2]/span[1]'
        self.gestVenVOICoLTXT = 'Comensales en el local'
        self.gestVenVOICoLDXPath = '//*[@id="currentcustomers"]'
        self.gestVenVOICoLDTXT = '0-0'
        self.gestVenVOICerXPath = '//*[@id="xModal"]/div/form/div[3]/button'
        self.gestVenVOICerTXT = 'Cerrar'

        # Visual Online Productos --> VOP
        self.gestVenVOPTitXPath = '//*[@id="viewProductsModal"]/div/div[1]/span'
        self.gestVenVOPTitTXT = 'PRODUCTOS VENDIDOS LTL FLEMING'
        self.gestVenVOPBusInput = '//*[@id="viewProductsModal"]/div/form/div[1]/div[1]/div/input'
        self.gestVenVOPBusValue = 'Barrita'
        self.gestVenVOPArtXPath = '//*[@id="viewProductsModal"]/div/form/div[1]/div[2]/table/thead/tr/th[1]'
        self.gestVenVOPArtTXT = 'Artículo'
        self.gestVenVOPCanXPath = '//*[@id="viewProductsModal"]/div/form/div[1]/div[2]/table/thead/tr/th[2]'
        self.gestVenVOPCanTXT = 'Cantidad'
        self.gestVenVOPTotXPath = '//*[@id="viewProductsModal"]/div/form/div[1]/div[2]/table/thead/tr/th[3]'
        self.gestVenVOPTotTXT = 'Total'
        self.gestVenVOPBus1XPath = '//*[@id="products"]/tr/td[1]'
        self.gestVenVOPBus1TXT = 'Barrita Tomate'
        self.gestVenVOPCan1Path = '//*[@id="products"]/tr/td[2]'
        self.gestVenVOPCan1TXT = '1'
        self.gestVenVOPTot1XPath = '//*[@id="products"]/tr/td[3]'
        self.gestVenVOPTot1TXT = '2.00 €'
        self.gestVenVOPExpXPath = '//*[@id="viewProductsModal"]/div/form/div[3]/button[1]' # Exportar productos
        self.gestVenVOPCerXPath = '//*[@id="viewProductsModal"]/div/form/div[3]/button[2]' # Cerrar productos
        self.gestVenVOPCer1TXT = 'Cerrar'

        # EXPORTAR --> Variables en Commons
        self.gestVenExpDesNFTXT = 'Historial%20de%20tickets_'  # Descarga de la exportacion del Nuevo Fichero
        self.gestVenExpDesProTXT = 'Productos%20LTL%20Fleming_'
        self.gestVenExpDesPr2TXT = 'Productos LTL Fleming'


        # BORRAR
        self.gestVenVODelXPath = '//*[@id="restaurant-list"]/div/div[1]/i'
        self.gestVenVODelID = 'deleteRestaurant()'
        self.gestVenVODelTitXPath = '//*[@id="deleteRestaurantModal"]/div/div[1]/span'
        self.gestVenVODelTitTXT = 'ELIMINAR LOCAL'
        self.gestVenVODelTit2XPath = '//*[@id="deleteRestaurantModal"]/div/form/div[1]/p'
        self.gestVenVODelTit2TXT = 'Por favor, contacte con soporte técnico para borrar este restaurante.'
        self.gestVenVODelCerXPath = '//*[@id="deleteRestaurantModal"]/div/form/div[3]/button'
        self.gestVenVODelCerTXT ='Cerrar'

        # Busqueda Avanzada
        self.gestVenVOBusAdvID = 'advancedSearch'
        self.gestVenVOBusAdvTXT = 'Búsqueda avanzada'
        self.gestVenVOBusAdvTitXPath ='//*[@id="advancedSearchModal"]/div/div[1]'
        self.gestVenVOBusAdvTitTXT = 'BÚSQUEDA AVANZADA'
        self.gestVenVOBusAdvNRecXPath = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[1]/div[1]'
        self.gestVenVOBusAdvNRecTXT = 'Número de recibo'
        self.gestVenVOBusAdvNRecInput = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[1]/div[1]/label/input'
        self.gestVenVOBusAdvNRecValue = 'NRecibo_'
        self.gestVenVOBusAdvNCieXPath = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[1]/div[2]'
        self.gestVenVOBusAdvNCieTXT = 'Número de cierre'
        self.gestVenVOBusAdvNCieInput = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[1]/div[2]/label/input'
        self.gestVenVOBusAdvNCieValue = 'NCierre_'
        self.gestVenVOBusAdvFIniXPath = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[2]/div[1]/label/div'
        self.gestVenVOBusAdvFIniTXT = 'Fecha inicio*'
        self.gestVenVOBusAdvFIniInput = '//*[@id="ui-datepicker-div"]/table/tbody/tr[4]/td[5]/a'  # 23/08/2024
        self.gestVenVOBusAdvFFinXPath = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[2]/div[2]/label/div'
        self.gestVenVOBusAdvFFinTXT = 'Fecha fin*'
        self.gestVenVOBusAdvFFinInput = '/html/body/div[19]/table/tbody/tr[5]/td[1]/a'  # 23/09/2024
        self.gestVenVOBusAdvNHabXPath = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[3]/div[1]'
        self.gestVenVOBusAdvNHabTXT = 'Nº Habitación'
        self.gestVenVOBusAdvNHabInput = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[3]/div[1]/label/input'
        self.gestVenVOBusAdvNHabValue = 'Habitación 2'
        self.gestVenVOBusAdvEmpXPath = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[3]/div[2]/label'
        self.gestVenVOBusAdvEmpTXT = 'Empleado'
        self.gestVenVOBusAdvEmpInput = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[3]/div[2]/label/div'
        self.gestVenVOBusAdvEmpValue = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[3]/div[2]/label/div/select/option[62]'
        self.gestVenVOBusAdvMesXPath = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[4]/div[1]'
        self.gestVenVOBusAdvMesTXT = 'Mesa'
        self.gestVenVOBusAdvMesInput = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[4]/div[1]/label/input'
        self.gestVenVOBusAdvMesValue = 'Mesa 5'
        self.gestVenVOBusAdvCajXPath = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[4]/div[2]/label'
        self.gestVenVOBusAdvCajTXT = 'Caja'
        self.gestVenVOBusAdvCajInput = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[4]/div[2]/label/div'
        self.gestVenVOBusAdvCajValue = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[4]/div[2]/label/div/select/option[3]'
        self.gestVenVOBusAdvFPaXPath = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[5]/div/label'
        self.gestVenVOBusAdvFPaTXT = 'Forma de pago'
        self.gestVenVOBusAdvFPaInput = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[5]/div/label/div'
        self.gestVenVOBusAdvFPaValue = '//*[@id="advancedSearchModal"]/div/form/div[1]/div[5]/div/label/div/select/option[3162]'
        self.gestVenVOBusAdvKOXPath = '//*[@id="advancedSearchModal"]/div/form/div[3]/button[1]'
        self.gestVenVOBusAdvKOTXT = 'Cancelar'
        self.gestVenVOBusAdvOKXPath = '//*[@id="advancedSearchModal"]/div/form/div[3]/button[2]'
        self.gestVenVOBusAdvOKTXT = 'Buscar'

        # Informes, Informes personalizados
        self.gestVenTitXPath = '//*[@id="contenttitle"]/div[1]/div'
        self.gestVenInfTit2XPath = '//*[@id="reports-space"]/form/div[1]/label'
        self.gestVenInfTit2TXT = 'Informe'
        self.gestVenInfExcID = 'excel'
        #self.gestVenFIniID = 'startDate'
        self.gestVenFIniTXT = 'Fecha inicio'
        #self.gestVenFFinID = 'endDate'
        self.gestVenFFinTXT = 'Fecha fin'
        self.gestVenISeID = 'reportType'
        self.gestVenInfFIniValue = "11/08/2024"
        self.gestVenInfFFinValue = "11/10/2024"

        # Informes
        self.gestVenInfTitTXT = 'INFORMES'
        self.gestVenInfExcTXT = 'Generar informe Excel'
        self.gestVenInfFIniXPath = '//*[@id="dateBetweenInput"]/label'
        self.gestVenInfFFinXPath = '//*[@id="dateBetweenInput"]/div'
        self.gestVenInfISeXPath = '/html/body/div[2]/div[2]/div[3]/div/form/div[1]/label/div/select/option[3]'   # Informe escogido
        self.gestVenInfISeTXT = 'Informe por producto (total)'
        self.gestVenExpDesInfTXT = 'Informe_Producto_Total_'
        self.gestVenInfFETXT = 'Informe por producto (Total)'

        # Informes personalizados
        self.gestVenIPTitTXT = 'INFORMES PERSONALIZADOS'
        self.gestVenIPSemXPath = '/html/body/div[2]/div[2]/div[3]/div/form/div[2]/label'
        self.gestVenIPSemTXT = 'Semana'
        self.gestVenIPAgnoXPath = '/html/body/div[2]/div[2]/div[3]/div/form/div[2]/div'
        self.gestVenIPAgnoTXT = 'Año'
        self.gestVenIPRFecXPath = '//*[@id="dates_week1"]/label'
        self.gestVenIPRFecTXT = 'Rango de fechas'
        self.gestVenIPExcTXT = 'Generar informe Excel por semana'
        self.gestVenIPFIniXPath = '//*[@id="reports-space"]/form/div[5]/label'
        self.gestVenIPFFinXPath = '//*[@id="reports-space"]/form/div[5]/div'
        self.gestVenIPRanID = 'excel_daily'
        self.gestVenIPRanTXT = 'Generar informe Excel por rango'
        self.gestVenIPISeXPath = '/html/body/div[2]/div[2]/div[3]/div/form/div[1]/label/div/select/option[3]'   # Informe escogido
        self.gestVenIPISeTXT = 'Informe de Takeaway'

        ####### PTE DE USAR (no funciona la busqueda) en Informe Personalizado
        self.gestVenIPISemInput = '/html/body/div[2]/div[2]/div[3]/div/form/div[1]/label/div/select'
        self.gestVenIPISemValue = 'semana?'
        self.gestVenIPIAgnoInput = '//*[@id="yearSelect"]/select'
        self.gestVenIPIAgnoValue = 'año?'










