class Settings:
    def __init__(self):
        super().__init__()
        self.url = 'https://tamus.hi-iberia.es/settings/notificationsettings'
        self.title = 'Ajustes de notificaciones'
        self.subtitleTXT = 'ALERTAS'   # Si se pone en minúsculas falla, en otros casos no...Revisar!!
        self.subtitleXPath = '//div[@id="alert-notifications"]//h2'
        self.inPendSettingTXT = 'Albarán entrante pendiente de validar'
        self.inPendSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[1]/span'
        self.imgInPendSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[1]/i'
        self.optInPendSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[1]/label/div'
        self.optInPendSettingInputClassXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[1]/label/input'
        self.dePendSettingTXT = 'Albarán salida pendiente de validar'
        self.dePendSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[2]/span'
        self.imgDePendSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[2]/i'
        self.optDePendSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[2]/label/div'
        self.optDePendSettingInputClassXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[2]/label/input'
        self.inRejSettingTXT = 'Albarán entrante rechazado'
        self.inRejSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[3]/span'
        self.imgInRejSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[3]/i'
        self.optInRejSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[3]/label/div'
        self.optInRejSettingInputClassXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[3]/label/input'
        self.deRejSettingTXT = 'Albarán salida rechazado'
        self.deRejSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[4]/span'
        self.imgDeRejSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[4]/i'
        self.optDeRejSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[4]/label/div'
        self.optDeRejSettingInputClassXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[4]/label/input'
        self.lowStoSettingTXT = 'Stock bajo en almacén'
        self.lowStoSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[5]/span'
        self.imgLowStoSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[5]/i'
        self.optLowStoSettingXPath = '/html/body/div[2]/div[2]/div[3]/div/div/div[5]/label'
        self.optLowStoSettingInputClassXPath = '//div[@id="alert-notifications"]/div[5]/label/input'